# Generated by Django 5.1 on 2024-08-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
