# Generated by Django 5.1 on 2024-08-27 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_image_file_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.medium'),
        ),
        migrations.AlterField(
            model_name='image',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.series'),
        ),
    ]
