# Generated by Django 5.1 on 2024-08-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_image_medium_alter_image_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
    ]
