# Generated by Django 5.1 on 2024-08-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_add_slugs_to_images_series_and_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_cover', to='gallery.image'),
        ),
    ]
