# Generated by Django 5.1 on 2024-08-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_series_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medium_cover', to='gallery.image'),
        ),
    ]
