# Generated by Django 5.1 on 2024-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_medium_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
