# Generated by Django 5.1 on 2024-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_series_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
