# Generated by Django 5.1 on 2024-09-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_image_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.TextField(blank=True),
        ),
    ]
