# Generated by Django 5.1 on 2024-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_image_image_focal_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
