# Generated by Django 5.1 on 2024-09-15 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
